### ISSUE TITLE
Variant and Genotype converters will need VCF header

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/convert#18]

**Comment by akmorrow13** [comment]
This would look something like this:

`
val codec = new VCFCodec()
    val vcfReader: AbstractFeatureReader[HtsjdkVariantContext, LineIterator] = AbstractFeatureReader.getFeatureReader(filename, codec)


   val header: VCFHeader = vcfReader.getHeader().asInstanceOf[VCFHeader]

    val converter = new VariantContextConverter(
      getHeaderLines(header),
      ValidationStringency.LENIENT, false)


  // defined in ADAM in VariantContextConverter line 266
def getHeaderLines(header: VCFHeader): Seq[VCFHeaderLine] = {
    (header.getFilterLines ++
      header.getFormatHeaderLines ++
      header.getInfoHeaderLines ++
      header.getOtherHeaderLines).toSeq
  }

`

**Comment by heuermh** [comment]
Yeah, but note the standard headers that ADAM uses are not exactly the same as the standard headers in htsjdk, because they don't actually follow the VCF specification.
