### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/convert#36]
Can we do a release of 0.2.0-SNAPSHOT to access GA4GH schemas when https://github.com/bigdatagenomics/bdg-convert/pull/35 is merged? This is for use in https://github.com/bigdatagenomics/mango/pull/316

**Comment by heuermh** [comment]
+1

**Comment by heuermh** [comment]
Fixed in commit f58b3451a561f579e272d2727b3a0f6651768ca4
