### ISSUE TITLE
Release version 0.3.0.

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/convert#51]
@akmorrow13 @jpdna Are there any other things necessary before cutting a version 0.3.0 release?

**Comment by akmorrow13** [comment]
@heuermh not to my knowledge!

**Comment by heuermh** [comment]
ok, I'll do it this afternoon

**Comment by heuermh** [comment]
Fixed by commit 1c07db9025012b3bd7ca0d39fccbb9e37779dbbb.  Will take a couple of hours to rsync to Maven Central.
